### ISSUE TITLE
Semantics of rename

### ISSUE THREAD

**Issue by hannesm** [mirage/mirage-kv#31]
//cc @palainp who proposed `rename`.

The intended semantics of `rename` when `source` is a prefix of `dest` (and `dest` a dictionary) is not clear to me:
- `rename ~source:"/" ~dest:"/foo/"`
- `rename ~source:"/foo" ~dest:"/foo/bar/"`

Should they error out? Or what is the desired behaviour?

**Comment by palainp** [comment]
Hi @hannesm, thanks for suggesting special cases that I hadn't thought of :)
From my pov (to use kv like an fs) it should return an error. But I don't see what type of error is most useful here :(
