### ISSUE TITLE
get_partial / set_partial / size: int or int64

### ISSUE THREAD

**Issue by hannesm** [mirage/mirage-kv#32]
While working on implementations, I'm curious whether `length` and `offset` in `get_partial`, `offset` in `set_partial`, and the return value of `size` should better be `int64` -- to enable safely reading and writing big data on 32bit systems as well (where int is pretty small).

//cc @palinp any preferences to use int (or was it mainly that you're on 64 bit systems anyways)?

**Comment by hannesm** [comment]
maybe worth using https://github.com/mirage/optint/ to avoid boxing? and 63 bit are sufficient...

**Comment by reynir** [comment]
I think for offset it makes sense to use int64, but for length I think int is fine since we can't make strings that are longer than what can fit in int.

**Comment by reynir** [comment]
And now I wonder what get should do if the content is so large it can't fit in a string..!

**Comment by hannesm** [comment]
> And now I wonder what get should do if the content is so large it can't fit in a string..!

with get_partial / set_partial we write and read only chunks of the data --> that should be fine ;)
