### ISSUE TITLE
`Mirage_kv.RO.list` does not specify if the returned keys are relative to `key` or absolute.

### ISSUE THREAD

**Issue by reynir** [mirage/mirage-kv#38]
I think the way forward is to look at what the implementations do - and if they agree we specify that behavior.

https://github.com/mirage/mirage-kv/blob/297015e2b22524f648ffdc87443fcd0f3ab59b23/src/mirage_kv.mli#L148-L153

**Comment by hannesm** [comment]
Ah, so git-kv and mirage-kv-mem provide the absolute key (by using `Mirage_kv.Key.add <sub> key`).

**Comment by reynir** [comment]
mirage-kv-mem did not return the absolute key in 3.1.0:

https://github.com/mirage/mirage-kv-mem/blob/v3.1.0/src/mirage_kv_mem.ml#L82-L90

I'm not opposed to returning absolute keys as in many cases it's convenient.

**Comment by hannesm** [comment]
Yes, the behaviour changed in mirage-kv-mem 3.2.0  / 3.2.1 (when mirage-kv 6.0.0 was supported): https://github.com/mirage/mirage-kv-mem/commit/0568c417edbdc1440443c78dfe2a784da737306b#diff-95712f84e44230209e7e8e709e156d76ef8783b82d3ba30a2143f07c9f087b3aR86 also in git-kv 0.0.2 https://github.com/roburio/git-kv/commit/d27fd751e1840fd11cb72648b02d073092fb2af4#diff-8eb05ae96d8254f6beb0a2694be54067bce03d90d9c60e4e625c98392e255d4aR415
